# Generated by Django 5.0.1 on 2024-04-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_enquete_lieu_enquete_questions_enquete_victime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice_autre_trouves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255, verbose_name='Equipe')),
                ('date_decouverte', models.DateField(verbose_name='Date de découverte')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.indice_autre')),
            ],
        ),
        migrations.CreateModel(
            name='Indice_chiffre_trouves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255, verbose_name='Equipe')),
                ('date_decouverte', models.DateField(verbose_name='Date de découverte')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.indice_chiffres')),
            ],
        ),
    ]
