# Generated by Django 5.0.1 on 2024-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_indice_autre_trouves_indice_chiffre_trouves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indice_chiffre_trouves',
            new_name='Indice_chiffres_trouves',
        ),
    ]
