# Generated by Django 5.0.1 on 2024-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_messagerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='date_envoie',
            field=models.DateTimeField(null=True, verbose_name='Date envoie'),
        ),
    ]
