# Generated by Django 5.0.1 on 2024-04-08 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_indice_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
