# Generated by Django 5.0.1 on 2024-04-09 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_enquete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='lieu',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Lieu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='questions',
            field=models.TextField(default='des questions', verbose_name='Questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquete',
            name='victime',
            field=models.CharField(default='Mr X', max_length=255, verbose_name='Victime'),
            preserve_default=False,
        ),
    ]
