# Generated by Django 5.0.1 on 2024-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice_autre_trouves',
            name='date_decouverte',
            field=models.DateTimeField(verbose_name='Date de découverte'),
        ),
        migrations.AlterField(
            model_name='indice_chiffres_trouves',
            name='date_decouverte',
            field=models.DateTimeField(verbose_name='Date de découverte'),
        ),
    ]
