# Generated by Django 5.0.1 on 2024-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_indice_autre_trouves_date_decouverte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices_trouves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('equipe', models.CharField(max_length=255, verbose_name='Equipe')),
                ('date_decouverte', models.DateTimeField(verbose_name='Date de découverte')),
            ],
        ),
        migrations.AlterModelOptions(
            name='enquete',
            options={'verbose_name': 'Enquête', 'verbose_name_plural': 'Enquêtes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Timer', 'verbose_name_plural': 'Timer'},
        ),
        migrations.AlterModelOptions(
            name='indice_autre',
            options={'verbose_name': 'Indice format libre', 'verbose_name_plural': 'Indices format libre'},
        ),
        migrations.AlterModelOptions(
            name='indice_autre_trouves',
            options={'verbose_name': 'Indice format libre trouvés', 'verbose_name_plural': 'Indices format libre trouvés'},
        ),
        migrations.AlterModelOptions(
            name='indice_chiffres',
            options={'verbose_name': 'Indice à chiffres', 'verbose_name_plural': 'Indices à chiffres'},
        ),
        migrations.AlterModelOptions(
            name='indice_chiffres_trouves',
            options={'verbose_name': 'Indice à chiffres trouvés', 'verbose_name_plural': 'Indices à chiffres trouvés'},
        ),
    ]
