# Generated by Django 5.0.1 on 2024-08-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_indices_trouves_alter_enquete_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255, verbose_name='Equipe')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
