# Generated by Django 5.0.1 on 2025-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_messagerie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice_autre_trouves',
            options={'verbose_name': 'Z - Indice format libre trouvés', 'verbose_name_plural': 'Z - Indices format libre trouvés'},
        ),
        migrations.AlterModelOptions(
            name='indice_chiffres_trouves',
            options={'verbose_name': 'Z - Indice à chiffres trouvés', 'verbose_name_plural': 'Z - Indices à chiffres trouvés'},
        ),
        migrations.AlterModelOptions(
            name='indices_trouves',
            options={'verbose_name': 'A - Indice trouvé', 'verbose_name_plural': 'A - Indices trouvés'},
        ),
        migrations.AddField(
            model_name='indice_autre',
            name='indice',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Indice'),
        ),
        migrations.AddField(
            model_name='indice_chiffres',
            name='indice',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Indice'),
        ),
    ]
